### ISSUE TITLE
n8n alerts not working

### ISSUE THREAD

**Issue by cybertricks** [maikroservice/wazuh-integrations#3]
I have followed the same steps but i am not getting the alerts in n8n tool. I checked the logs in the logs it says that DEBUG: Command ran successfully.

Discord was working fine but the n8n not showing any results.

**Comment by RyanInsolencee** [comment]
did you ever get it fixed? and if how so
im kind of facing the same issue

**Comment by maikroservice** [comment]
hey - could you tell me your process for setting this up in a step-by-step manner?
Because for the alerts to show up in n8n in a useful manner you need to setup a workflow first

**Comment by RyanInsolencee** [comment]
i got a question in regards to adding additional fields to extract for some reason when i add in any additional fields the whole script stops working and i dont see anything on my n8n currently running it as the default config
the logs are coming from my fw > wazuh > n8n > hive

**Comment by maikroservice** [comment]
@RyanInsolencee do you have the code available for review somewhere? Generally, you need to add the parameters to the configuration script (custom-n8n.py) first, then you should be able to also include them in the n8n workflow

**Comment by maikroservice** [comment]
because I am not exactly sure how this went wrong I made a tutorial on how I set this up for my lab: 

https://view.flodesk.com/emails/66af856200c639313ae149d3

most likely it's an issue with a missing/misconfigured reverse proxy in your setup, I hope this helps

**Comment by RyanInsolencee** [comment]
im running n8n in npm anyways but i got it working , thanks alot
just do have one question in your experience configuring the integration with `<rule_id>` or `<level>` did you come across any problems?

**Comment by maikroservice** [comment]
> 
> 
> im running n8n in npm anyways but i got it working , thanks alot
> 
> just do have one question in your experience configuring the integration with `<rule_id>` or `<level>` did you come across any problems?
> 
> 

Can you share an example what you mean? Would you want to only trigger the integration for specific rules or above certain level tresholds?

**Comment by RyanInsolencee** [comment]
yeah right now i have it set at `<level>5</level>` previously i wanted to take only a certain `<rule_id>101001,101002</rule_id>` but i could not get it to work so my workflow just became longer but at this rate ive taken out my hive integration and stuck it in n8n
